# Generated by Django 2.2.8 on 2020-01-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='clothes_datefield',
            field=models.DateField(blank=True, default='2012-12-12', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='petrol_datefield',
            field=models.DateField(blank=True, default='2012-12-12', null=True),
        ),
    ]
