# Generated by Django 2.2.8 on 2020-01-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManager', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='clothes_datefield',
        ),
        migrations.RemoveField(
            model_name='category',
            name='petrol_datefield',
        ),
    ]
