# Generated by Django 2.2.8 on 2019-12-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManager', '0019_auto_20191227_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='foodname',
        ),
        migrations.AddField(
            model_name='date',
            name='foodname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
